one dir build

diff --git a/debian/ns2/DEBIAN/postinst b/debian/ns2/DEBIAN/postinst
--- a/debian/ns2/DEBIAN/postinst
+++ b/debian/ns2/DEBIAN/postinst
@@ -1,6 +1,25 @@
-#!/bin/sh
+#!/bin/bash
 set -e
-# Automatically added by dh_installsystemd/13.11.4
+
+case "$1" in
+    configure)
+
+        firewall-cmd --reload
+        firewall-cmd --permanent --zone=public --add-service=ns2
+        firewall-cmd --permanent --zone=public --add-service=ssh
+        firewall-cmd --permanent --zone=public --add-service=http
+        firewall-cmd --permanent --zone=public --add-service=https
+
+        # Restart snmpd
+        systemctl restart firewalld 2>/dev/null || true
+        ;;
+    
+    abort-upgrade|abort-remove|abort-deconfigure)
+        # Handle failure cases
+        ;;
+esac
+
+# Automatically added by dh_installsystemd/13.14.1ubuntu5
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# The following line should be removed in trixie or trixie+1
 	deb-systemd-helper unmask 'ns2-dbus.service' >/dev/null || true
@@ -17,7 +36,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.11.4
+# Automatically added by dh_installsystemd/13.14.1ubuntu5
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# The following line should be removed in trixie or trixie+1
 	deb-systemd-helper unmask 'ns2-ui.service' >/dev/null || true
@@ -34,7 +53,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.11.4
+# Automatically added by dh_installsystemd/13.14.1ubuntu5
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -47,3 +66,6 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
+
+
+exit 0
